"""make_category_id_nullable

Revision ID: 02c653e46f38
Revises: 18c707a8a424
Create Date: 2026-08-25 20:31:41.369605
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '02c653e46f38'
down_revision: Union[str, None] = '18c707a8a424'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gastos_reserva_comprobar_facturas', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('viaticos_facturas', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('viaticos_facturas', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('gastos_reserva_comprobar_facturas', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
