"""add_vessel_requests

Revision ID: 0849f33f0829
Revises: d7310d0a1359
Create Date: 2026-06-01 20:19:41.151972
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '0849f33f0829'
down_revision: Union[str, None] = 'd7310d0a1359'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cruise_plans', sa.Column('vessel_request_id', sa.Integer(), nullable=True))
    op.add_column('cruise_plans', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('cruise_plans', sa.Column('scientific_leader', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_cruise_plans_created_by_id'), 'cruise_plans', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_cruise_plans_vessel_request_id'), 'cruise_plans', ['vessel_request_id'], unique=False)
    op.create_foreign_key(None, 'cruise_plans', 'vessel_requests', ['vessel_request_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'cruise_plans', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cruise_plans', type_='foreignkey')
    op.drop_constraint(None, 'cruise_plans', type_='foreignkey')
    op.drop_index(op.f('ix_cruise_plans_vessel_request_id'), table_name='cruise_plans')
    op.drop_index(op.f('ix_cruise_plans_created_by_id'), table_name='cruise_plans')
    op.drop_column('cruise_plans', 'scientific_leader')
    op.drop_column('cruise_plans', 'created_by_id')
    op.drop_column('cruise_plans', 'vessel_request_id')
    # ### end Alembic commands ###
