"""add_participant_profile_id_to_users

Revision ID: 14a416660e57
Revises: cfd7f1f783b9
Create Date: 2026-06-02 19:05:08.511996
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '14a416660e57'
down_revision: Union[str, None] = 'cfd7f1f783b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('participant_profile_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'participant_profiles', ['participant_profile_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'participant_profile_id')
    # ### end Alembic commands ###
