"""add_sat_status_to_grc_and_viatico_invoices

Revision ID: 18c707a8a424
Revises: 58d51563c5b9
Create Date: 2026-08-25 17:35:47.657725
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '18c707a8a424'
down_revision: Union[str, None] = '58d51563c5b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gastos_reserva_comprobar_facturas', sa.Column('sat_status', sa.String(length=50), nullable=True))
    op.add_column('gastos_reserva_comprobar_facturas', sa.Column('sat_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('viaticos_facturas', sa.Column('sat_status', sa.String(length=50), nullable=True))
    op.add_column('viaticos_facturas', sa.Column('sat_verified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viaticos_facturas', 'sat_verified_at')
    op.drop_column('viaticos_facturas', 'sat_status')
    op.drop_column('gastos_reserva_comprobar_facturas', 'sat_verified_at')
    op.drop_column('gastos_reserva_comprobar_facturas', 'sat_status')
    # ### end Alembic commands ###
