"""add_curp_to_participant_profiles

Revision ID: 1bd5147ad5fc
Revises: d04c8b6a0b82
Create Date: 2026-06-23 19:29:44.151074
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '1bd5147ad5fc'
down_revision: Union[str, None] = 'd04c8b6a0b82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant_profiles', sa.Column('curp', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'participant_profiles', ['curp'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'participant_profiles', type_='unique')
    op.drop_column('participant_profiles', 'curp')
    # ### end Alembic commands ###
