"""add_firma_responsable_to_viaticos

Revision ID: 20925c67f23c
Revises: cbc7fd02b08d
Create Date: 2026-08-25 22:33:22.943482
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '20925c67f23c'
down_revision: Union[str, None] = 'cbc7fd02b08d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viaticos', sa.Column('firma_responsable_nombre', sa.String(length=200), nullable=True))
    op.add_column('viaticos', sa.Column('firma_responsable_fecha', sa.DateTime(timezone=True), nullable=True))
    op.add_column('viaticos', sa.Column('firma_responsable_hash', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viaticos', 'firma_responsable_hash')
    op.drop_column('viaticos', 'firma_responsable_fecha')
    op.drop_column('viaticos', 'firma_responsable_nombre')
    # ### end Alembic commands ###
