"""add_vehicle_fuel_to_billing

Revision ID: 2380e3dc2787
Revises: 79f09474f4e1
Create Date: 2026-06-09 18:50:06.099454
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '2380e3dc2787'
down_revision: Union[str, None] = '79f09474f4e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cruise_billings', sa.Column('vehicle_fuel_liters', sa.Float(), nullable=True))
    op.add_column('cruise_billings', sa.Column('vehicle_fuel_price_per_liter', sa.Float(), nullable=True))
    op.add_column('cruise_billings', sa.Column('vehicle_fuel_cost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cruise_billings', 'vehicle_fuel_cost')
    op.drop_column('cruise_billings', 'vehicle_fuel_price_per_liter')
    op.drop_column('cruise_billings', 'vehicle_fuel_liters')
    # ### end Alembic commands ###
