"""add_personnel_uploads

Revision ID: 2cf21eb9fb51
Revises: a47ed77af1d0
Create Date: 2026-06-03 17:35:32.748937
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '2cf21eb9fb51'
down_revision: Union[str, None] = 'a47ed77af1d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personnel', sa.Column('photo_url', sa.String(length=500), nullable=True))
    op.add_column('personnel', sa.Column('id_document_url', sa.String(length=500), nullable=True))
    op.add_column('personnel', sa.Column('seamans_book_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personnel', 'seamans_book_url')
    op.drop_column('personnel', 'id_document_url')
    op.drop_column('personnel', 'photo_url')
    # ### end Alembic commands ###
