"""create projects table and associate with cruises

Revision ID: 3467bab0ea88
Revises: 874179f79b2e
Create Date: 2026-06-22 17:58:24.959775
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '3467bab0ea88'
down_revision: Union[str, None] = '874179f79b2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cruise_plans', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_cruise_plans_project_id'), 'cruise_plans', ['project_id'], unique=False)
    op.create_foreign_key(None, 'cruise_plans', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.add_column('vessel_requests', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_vessel_requests_project_id'), 'vessel_requests', ['project_id'], unique=False)
    op.create_foreign_key(None, 'vessel_requests', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vessel_requests', type_='foreignkey')
    op.drop_index(op.f('ix_vessel_requests_project_id'), table_name='vessel_requests')
    op.drop_column('vessel_requests', 'project_id')
    op.drop_constraint(None, 'cruise_plans', type_='foreignkey')
    op.drop_index(op.f('ix_cruise_plans_project_id'), table_name='cruise_plans')
    op.drop_column('cruise_plans', 'project_id')
    # ### end Alembic commands ###
