"""add_asistente_id_to_grc_and_viaticos

Revision ID: 3eb398489fb2
Revises: ae8954607377
Create Date: 2026-08-24 21:26:10.092464
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '3eb398489fb2'
down_revision: Union[str, None] = 'ae8954607377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gastos_reserva_comprobar', sa.Column('asistente_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'gastos_reserva_comprobar', 'users', ['asistente_id'], ['id'], ondelete='SET NULL')
    op.add_column('viaticos', sa.Column('asistente_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'viaticos', 'users', ['asistente_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'viaticos', type_='foreignkey')
    op.drop_column('viaticos', 'asistente_id')
    op.drop_constraint(None, 'gastos_reserva_comprobar', type_='foreignkey')
    op.drop_column('gastos_reserva_comprobar', 'asistente_id')
    # ### end Alembic commands ###
