"""add_viaticos_module

Revision ID: 406e34941ad2
Revises: 27e1d5b58184
Create Date: 2026-08-20 21:31:31.445499
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '406e34941ad2'
down_revision: Union[str, None] = '27e1d5b58184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
