"""add_vessel_rates_and_cruise_billing

Revision ID: 4a4129f7e17a
Revises: 5a4a94c56944
Create Date: 2026-06-08 20:26:13.443709
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '4a4129f7e17a'
down_revision: Union[str, None] = '5a4a94c56944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
