"""add_grc_items_and_signature_hashes

Revision ID: 58d51563c5b9
Revises: 3eb398489fb2
Create Date: 2026-08-24 21:49:09.022786
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '58d51563c5b9'
down_revision: Union[str, None] = '3eb398489fb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gastos_reserva_comprobar', sa.Column('firma_solicitante_hash', sa.String(length=500), nullable=True))
    op.add_column('gastos_reserva_comprobar', sa.Column('firma_revisor_hash', sa.String(length=500), nullable=True))
    op.add_column('gastos_reserva_comprobar', sa.Column('firma_jefe_hash', sa.String(length=500), nullable=True))
    op.add_column('gastos_reserva_comprobar', sa.Column('firma_adquisiciones_hash', sa.String(length=500), nullable=True))
    op.add_column('gastos_reserva_comprobar', sa.Column('firma_director_hash', sa.String(length=500), nullable=True))
    op.add_column('gastos_reserva_comprobar', sa.Column('firma_tesoreria_hash', sa.String(length=500), nullable=True))
    op.add_column('gastos_reserva_comprobar', sa.Column('firma_contabilidad_hash', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gastos_reserva_comprobar', 'firma_contabilidad_hash')
    op.drop_column('gastos_reserva_comprobar', 'firma_tesoreria_hash')
    op.drop_column('gastos_reserva_comprobar', 'firma_director_hash')
    op.drop_column('gastos_reserva_comprobar', 'firma_adquisiciones_hash')
    op.drop_column('gastos_reserva_comprobar', 'firma_jefe_hash')
    op.drop_column('gastos_reserva_comprobar', 'firma_revisor_hash')
    op.drop_column('gastos_reserva_comprobar', 'firma_solicitante_hash')
    # ### end Alembic commands ###
