"""add_fuel_logs_table

Revision ID: 5a4a94c56944
Revises: fb1bd777c7ef
Create Date: 2026-06-08 19:17:53.398634
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '5a4a94c56944'
down_revision: Union[str, None] = 'fb1bd777c7ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
