"""add_participant_profiles_catalog

Revision ID: 6491036a5836
Revises: e30d83219034
Create Date: 2026-05-26 18:33:29.470214
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '6491036a5836'
down_revision: Union[str, None] = 'e30d83219034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cruise_participants', sa.Column('participant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_cruise_participants_participant_id'), 'cruise_participants', ['participant_id'], unique=False)
    op.drop_constraint('cruise_participants_personnel_id_fkey', 'cruise_participants', type_='foreignkey')
    op.create_foreign_key(None, 'cruise_participants', 'participant_profiles', ['participant_id'], ['id'], ondelete='CASCADE')
    op.drop_column('cruise_participants', 'first_name')
    op.drop_column('cruise_participants', 'id_document_expiry')
    op.drop_column('cruise_participants', 'id_document_url')
    op.drop_column('cruise_participants', 'id_document_type')
    op.drop_column('cruise_participants', 'personnel_id')
    op.drop_column('cruise_participants', 'institution')
    op.drop_column('cruise_participants', 'nationality')
    op.drop_column('cruise_participants', 'id_document_number')
    op.drop_column('cruise_participants', 'last_name')
    op.drop_column('cruise_participants', 'photo_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cruise_participants', sa.Column('photo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('cruise_participants', sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('cruise_participants', sa.Column('id_document_number', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('cruise_participants', sa.Column('nationality', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('cruise_participants', sa.Column('institution', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('cruise_participants', sa.Column('personnel_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('cruise_participants', sa.Column('id_document_type', postgresql.ENUM('INE', 'PASAPORTE', 'OTRO', name='iddocumenttype'), autoincrement=False, nullable=True))
    op.add_column('cruise_participants', sa.Column('id_document_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('cruise_participants', sa.Column('id_document_expiry', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('cruise_participants', sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cruise_participants', type_='foreignkey')
    op.create_foreign_key('cruise_participants_personnel_id_fkey', 'cruise_participants', 'personnel', ['personnel_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_cruise_participants_participant_id'), table_name='cruise_participants')
    op.drop_column('cruise_participants', 'participant_id')
    # ### end Alembic commands ###
