"""add invoices_details to petty_cash_counts

Revision ID: 74836363a5b4
Revises: bd45f3c079e7
Create Date: 2026-06-18 20:57:46.682929
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '74836363a5b4'
down_revision: Union[str, None] = 'bd45f3c079e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('petty_cash_counts', sa.Column('invoices_details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('petty_cash_counts', 'invoices_details')
    # ### end Alembic commands ###
