"""add_vessel_order_files_to_billing

Revision ID: 79f09474f4e1
Revises: 4a4129f7e17a
Create Date: 2026-06-09 18:29:55.549347
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '79f09474f4e1'
down_revision: Union[str, None] = '4a4129f7e17a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cruise_billings', sa.Column('vessel_order_filename', sa.String(length=300), nullable=True))
    op.add_column('cruise_billings', sa.Column('vessel_order_uploaded_at', sa.DateTime(), nullable=True))
    op.add_column('cruise_billings', sa.Column('signed_vessel_order_filename', sa.String(length=300), nullable=True))
    op.add_column('cruise_billings', sa.Column('signed_vessel_order_uploaded_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cruise_billings', 'signed_vessel_order_uploaded_at')
    op.drop_column('cruise_billings', 'signed_vessel_order_filename')
    op.drop_column('cruise_billings', 'vessel_order_uploaded_at')
    op.drop_column('cruise_billings', 'vessel_order_filename')
    # ### end Alembic commands ###
