"""add_cruise_billing_id_to_transactions

Revision ID: 7de66823f03c
Revises: 1bd5147ad5fc
Create Date: 2026-06-23 19:32:31.911225
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '7de66823f03c'
down_revision: Union[str, None] = '1bd5147ad5fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_transactions', sa.Column('cruise_billing_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'account_transactions', 'cruise_billings', ['cruise_billing_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account_transactions', type_='foreignkey')
    op.drop_column('account_transactions', 'cruise_billing_id')
    # ### end Alembic commands ###
