"""add_is_cruise_leader_to_participants

Revision ID: aa62e3cf3eff
Revises: e9537636de50
Create Date: 2026-06-04 22:20:51.638214
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'aa62e3cf3eff'
down_revision: Union[str, None] = 'e9537636de50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cruise_participants', sa.Column('is_cruise_leader', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cruise_participants', 'is_cruise_leader')
    # ### end Alembic commands ###
