"""add_grc_module

Revision ID: aca981671ab4
Revises: 7de66823f03c
Create Date: 2026-08-03 22:17:33.269164
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'aca981671ab4'
down_revision: Union[str, None] = '7de66823f03c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gastos_reserva_comprobar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folio_episa', sa.String(length=100), nullable=False),
    sa.Column('solicitante_id', sa.Integer(), nullable=True),
    sa.Column('fecha_solicitud', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('fecha_pago_servicio', sa.Date(), nullable=True),
    sa.Column('justificacion', sa.Text(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('monto_solicitado', sa.Float(), nullable=False),
    sa.Column('monto_comprobado', sa.Float(), nullable=False),
    sa.Column('monto_devuelto', sa.Float(), nullable=False),
    sa.Column('monto_saldo_favor', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('solicitud_pdf_path', sa.String(length=500), nullable=True),
    sa.Column('comprobacion_pdf_path', sa.String(length=500), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('project_name', sa.String(length=300), nullable=True),
    sa.Column('firma_solicitante_nombre', sa.String(length=200), nullable=True),
    sa.Column('firma_solicitante_fecha', sa.DateTime(timezone=True), nullable=True),
    sa.Column('firma_revisor_nombre', sa.String(length=200), nullable=True),
    sa.Column('firma_revisor_fecha', sa.DateTime(timezone=True), nullable=True),
    sa.Column('firma_jefe_nombre', sa.String(length=200), nullable=True),
    sa.Column('firma_jefe_fecha', sa.DateTime(timezone=True), nullable=True),
    sa.Column('firma_adquisiciones_nombre', sa.String(length=200), nullable=True),
    sa.Column('firma_adquisiciones_fecha', sa.DateTime(timezone=True), nullable=True),
    sa.Column('firma_director_nombre', sa.String(length=200), nullable=True),
    sa.Column('firma_director_fecha', sa.DateTime(timezone=True), nullable=True),
    sa.Column('firma_tesoreria_nombre', sa.String(length=200), nullable=True),
    sa.Column('firma_tesoreria_fecha', sa.DateTime(timezone=True), nullable=True),
    sa.Column('firma_contabilidad_nombre', sa.String(length=200), nullable=True),
    sa.Column('firma_contabilidad_fecha', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tiempo_revisor_horas', sa.Float(), nullable=True),
    sa.Column('tiempo_jefe_horas', sa.Float(), nullable=True),
    sa.Column('tiempo_director_horas', sa.Float(), nullable=True),
    sa.Column('tiempo_tesoreria_horas', sa.Float(), nullable=True),
    sa.Column('tiempo_contabilidad_horas', sa.Float(), nullable=True),
    sa.Column('tiempo_total_dias', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['financial_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['solicitante_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gastos_reserva_comprobar_folio_episa'), 'gastos_reserva_comprobar', ['folio_episa'], unique=True)
    op.create_index(op.f('ix_gastos_reserva_comprobar_id'), 'gastos_reserva_comprobar', ['id'], unique=False)
    op.create_table('gastos_reserva_comprobar_facturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gasto_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=100), nullable=True),
    sa.Column('folio', sa.String(length=50), nullable=True),
    sa.Column('serie', sa.String(length=50), nullable=True),
    sa.Column('emisor_rfc', sa.String(length=20), nullable=False),
    sa.Column('emisor_nombre', sa.String(length=200), nullable=False),
    sa.Column('receptor_rfc', sa.String(length=20), nullable=True),
    sa.Column('receptor_nombre', sa.String(length=200), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('iva', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('moneda', sa.String(length=10), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(timezone=True), nullable=True),
    sa.Column('xml_filename', sa.String(length=300), nullable=True),
    sa.Column('pdf_filename', sa.String(length=300), nullable=True),
    sa.Column('is_manual', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('registered_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['financial_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['gasto_id'], ['gastos_reserva_comprobar.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registered_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gastos_reserva_comprobar_facturas_gasto_id'), 'gastos_reserva_comprobar_facturas', ['gasto_id'], unique=False)
    op.create_index(op.f('ix_gastos_reserva_comprobar_facturas_id'), 'gastos_reserva_comprobar_facturas', ['id'], unique=False)
    op.create_index(op.f('ix_gastos_reserva_comprobar_facturas_uuid'), 'gastos_reserva_comprobar_facturas', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gastos_reserva_comprobar_facturas_uuid'), table_name='gastos_reserva_comprobar_facturas')
    op.drop_index(op.f('ix_gastos_reserva_comprobar_facturas_id'), table_name='gastos_reserva_comprobar_facturas')
    op.drop_index(op.f('ix_gastos_reserva_comprobar_facturas_gasto_id'), table_name='gastos_reserva_comprobar_facturas')
    op.drop_table('gastos_reserva_comprobar_facturas')
    op.drop_index(op.f('ix_gastos_reserva_comprobar_id'), table_name='gastos_reserva_comprobar')
    op.drop_index(op.f('ix_gastos_reserva_comprobar_folio_episa'), table_name='gastos_reserva_comprobar')
    op.drop_table('gastos_reserva_comprobar')
    # ### end Alembic commands ###
