"""change_viaticos_traveler_to_personnel

Revision ID: ae8954607377
Revises: fffee0f46154
Create Date: 2026-08-20 22:01:39.312418
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'ae8954607377'
down_revision: Union[str, None] = 'fffee0f46154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viaticos', sa.Column('personal_id', sa.Integer(), nullable=True))
    op.drop_constraint('viaticos_solicitante_id_fkey', 'viaticos', type_='foreignkey')
    op.create_foreign_key(None, 'viaticos', 'personnel', ['personal_id'], ['id'], ondelete='SET NULL')
    op.drop_column('viaticos', 'solicitante_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viaticos', sa.Column('solicitante_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'viaticos', type_='foreignkey')
    op.create_foreign_key('viaticos_solicitante_id_fkey', 'viaticos', 'users', ['solicitante_id'], ['id'], ondelete='SET NULL')
    op.drop_column('viaticos', 'personal_id')
    # ### end Alembic commands ###
