"""add financial and petty cash tables

Revision ID: b4eca7d9b202
Revises: 2380e3dc2787
Create Date: 2026-06-16 16:37:57.977125
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'b4eca7d9b202'
down_revision: Union[str, None] = '2380e3dc2787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
