"""add_sat_validation_fields

Revision ID: bd45f3c079e7
Revises: b4eca7d9b202
Create Date: 2026-06-17 18:39:05.554644
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'bd45f3c079e7'
down_revision: Union[str, None] = 'b4eca7d9b202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('petty_cash_invoices', sa.Column('sat_status', sa.String(length=50), nullable=True))
    op.add_column('petty_cash_invoices', sa.Column('sat_verified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('petty_cash_invoices', 'sat_verified_at')
    op.drop_column('petty_cash_invoices', 'sat_status')
    # ### end Alembic commands ###
