"""add_detailed_viaticos_rubros

Revision ID: cbc7fd02b08d
Revises: e8e6b4f56c7f
Create Date: 2026-08-25 20:55:15.676227
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'cbc7fd02b08d'
down_revision: Union[str, None] = 'e8e6b4f56c7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viaticos', sa.Column('monto_arrendamiento_vehiculos', sa.Float(), nullable=True))
    op.add_column('viaticos', sa.Column('monto_pasaje_terrestre', sa.Float(), nullable=True))
    op.add_column('viaticos', sa.Column('monto_gasolina', sa.Float(), nullable=True))
    
    # Rellenar filas existentes
    op.execute("UPDATE viaticos SET monto_arrendamiento_vehiculos = 0.0, monto_pasaje_terrestre = 0.0, monto_gasolina = 0.0")
    
    # Hacer columnas NOT NULL
    op.alter_column('viaticos', 'monto_arrendamiento_vehiculos', nullable=False)
    op.alter_column('viaticos', 'monto_pasaje_terrestre', nullable=False)
    op.alter_column('viaticos', 'monto_gasolina', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viaticos', 'monto_gasolina')
    op.drop_column('viaticos', 'monto_pasaje_terrestre')
    op.drop_column('viaticos', 'monto_arrendamiento_vehiculos')
    # ### end Alembic commands ###
