"""add_created_by_to_participants

Revision ID: cfd7f1f783b9
Revises: 0849f33f0829
Create Date: 2026-06-02 18:29:10.759029
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'cfd7f1f783b9'
down_revision: Union[str, None] = '0849f33f0829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant_profiles', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_participant_profiles_created_by_id'), 'participant_profiles', ['created_by_id'], unique=False)
    op.create_foreign_key(None, 'participant_profiles', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'participant_profiles', type_='foreignkey')
    op.drop_index(op.f('ix_participant_profiles_created_by_id'), table_name='participant_profiles')
    op.drop_column('participant_profiles', 'created_by_id')
    # ### end Alembic commands ###
