"""add_cruise_responsible_column

Revision ID: d04c8b6a0b82
Revises: 3467bab0ea88
Create Date: 2026-06-23 18:59:55.770534
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'd04c8b6a0b82'
down_revision: Union[str, None] = '3467bab0ea88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cruise_plans', sa.Column('cruise_responsible', sa.String(length=200), nullable=True))
    op.add_column('vessel_requests', sa.Column('cruise_responsible', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vessel_requests', 'cruise_responsible')
    op.drop_column('cruise_plans', 'cruise_responsible')
    # ### end Alembic commands ###
