"""add_viaticos_detailed_amounts

Revision ID: d0adef8639f1
Revises: 02c653e46f38
Create Date: 2026-08-25 20:47:29.482152
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'd0adef8639f1'
down_revision: Union[str, None] = '02c653e46f38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viaticos', sa.Column('monto_viaticos', sa.Float(), nullable=True))
    op.add_column('viaticos', sa.Column('monto_pasaje_aereo', sa.Float(), nullable=True))
    op.add_column('viaticos', sa.Column('monto_hospedaje_paquete', sa.Float(), nullable=True))
    
    # Rellenar filas existentes
    op.execute("UPDATE viaticos SET monto_viaticos = 0.0, monto_pasaje_aereo = 0.0, monto_hospedaje_paquete = 0.0")
    
    # Hacer columnas NOT NULL
    op.alter_column('viaticos', 'monto_viaticos', nullable=False)
    op.alter_column('viaticos', 'monto_pasaje_aereo', nullable=False)
    op.alter_column('viaticos', 'monto_hospedaje_paquete', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viaticos', 'monto_hospedaje_paquete')
    op.drop_column('viaticos', 'monto_pasaje_aereo')
    op.drop_column('viaticos', 'monto_viaticos')
    # ### end Alembic commands ###
