"""add cruise relation to logbook

Revision ID: d7310d0a1359
Revises: fdcad85a75b1
Create Date: 2026-05-29 21:12:26.398532
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'd7310d0a1359'
down_revision: Union[str, None] = 'fdcad85a75b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logbook_entries', sa.Column('cruise_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_logbook_entries_cruise_id'), 'logbook_entries', ['cruise_id'], unique=False)
    op.create_foreign_key(None, 'logbook_entries', 'cruise_plans', ['cruise_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'logbook_entries', type_='foreignkey')
    op.drop_index(op.f('ix_logbook_entries_cruise_id'), table_name='logbook_entries')
    op.drop_column('logbook_entries', 'cruise_id')
    # ### end Alembic commands ###
