"""add_trip_report_to_cruise_plans

Revision ID: e20df57efd44
Revises: fac8797bb5af
Create Date: 2026-06-05 19:52:18.001948
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'e20df57efd44'
down_revision: Union[str, None] = 'fac8797bb5af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cruise_plans', sa.Column('trip_report', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cruise_plans', 'trip_report')
    # ### end Alembic commands ###
