"""add_cruise_participants

Revision ID: e30d83219034
Revises: ff82374677ad
Create Date: 2026-05-26 18:22:07.945737
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'e30d83219034'
down_revision: Union[str, None] = 'ff82374677ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'maintenance_interval_hours')
    op.create_index(op.f('ix_inventory_items_equipment_id'), 'inventory_items', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_maintenance_records_equipment_id'), 'maintenance_records', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_maintenance_records_routine_id'), 'maintenance_records', ['routine_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_records_routine_id'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_equipment_id'), table_name='maintenance_records')
    op.drop_index(op.f('ix_inventory_items_equipment_id'), table_name='inventory_items')
    op.add_column('equipment', sa.Column('maintenance_interval_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
