"""add_campaign_plan_fields

Revision ID: eaf7cca44bad
Revises: 6491036a5836
Create Date: 2026-05-26 19:54:09.280681
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'eaf7cca44bad'
down_revision: Union[str, None] = '6491036a5836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cruise_plans', sa.Column('cruise_number', sa.String(length=100), nullable=True))
    op.add_column('cruise_plans', sa.Column('project_name', sa.String(length=300), nullable=True))
    op.add_column('cruise_plans', sa.Column('study_area', sa.Text(), nullable=True))
    op.add_column('cruise_plans', sa.Column('disciplines', sa.Text(), nullable=True))
    op.add_column('cruise_plans', sa.Column('funding_source', sa.String(length=300), nullable=True))
    op.create_index(op.f('ix_cruise_plans_cruise_number'), 'cruise_plans', ['cruise_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cruise_plans_cruise_number'), table_name='cruise_plans')
    op.drop_column('cruise_plans', 'funding_source')
    op.drop_column('cruise_plans', 'disciplines')
    op.drop_column('cruise_plans', 'study_area')
    op.drop_column('cruise_plans', 'project_name')
    op.drop_column('cruise_plans', 'cruise_number')
    # ### end Alembic commands ###
