"""add_actual_track_to_cruise_plans

Revision ID: fac8797bb5af
Revises: aa62e3cf3eff
Create Date: 2026-06-05 19:43:37.512673
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'fac8797bb5af'
down_revision: Union[str, None] = 'aa62e3cf3eff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cruise_plans', sa.Column('actual_track', sa.JSON(), nullable=True))
    op.add_column('cruise_plans', sa.Column('actual_track_filename', sa.String(length=300), nullable=True))
    op.add_column('cruise_plans', sa.Column('actual_track_uploaded_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cruise_plans', 'actual_track_uploaded_at')
    op.drop_column('cruise_plans', 'actual_track_filename')
    op.drop_column('cruise_plans', 'actual_track')
    # ### end Alembic commands ###
