"""Add speed and activity to waypoints and vessel

Revision ID: ff82374677ad
Revises: 
Create Date: 2026-05-20 17:09:42.369399
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'ff82374677ad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cruise_waypoints', sa.Column('speed_knots', sa.Float(), nullable=True))
    op.add_column('cruise_waypoints', sa.Column('activity', sa.Text(), nullable=True))
    op.add_column('cruise_waypoints', sa.Column('duration_hours', sa.Float(), nullable=True))
    op.add_column('vessels', sa.Column('max_speed_knots', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vessels', 'max_speed_knots')
    op.drop_column('cruise_waypoints', 'duration_hours')
    op.drop_column('cruise_waypoints', 'activity')
    op.drop_column('cruise_waypoints', 'speed_knots')
    # ### end Alembic commands ###
