"""add_viaticos_signatures

Revision ID: fffee0f46154
Revises: 406e34941ad2
Create Date: 2026-08-20 21:49:12.016679
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'fffee0f46154'
down_revision: Union[str, None] = '406e34941ad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viaticos', sa.Column('firma_solicitante_nombre', sa.String(length=200), nullable=True))
    op.add_column('viaticos', sa.Column('firma_solicitante_fecha', sa.DateTime(timezone=True), nullable=True))
    op.add_column('viaticos', sa.Column('firma_solicitante_hash', sa.String(length=500), nullable=True))
    op.add_column('viaticos', sa.Column('firma_jefe_nombre', sa.String(length=200), nullable=True))
    op.add_column('viaticos', sa.Column('firma_jefe_fecha', sa.DateTime(timezone=True), nullable=True))
    op.add_column('viaticos', sa.Column('firma_jefe_hash', sa.String(length=500), nullable=True))
    op.add_column('viaticos', sa.Column('firma_revisor_nombre', sa.String(length=200), nullable=True))
    op.add_column('viaticos', sa.Column('firma_revisor_fecha', sa.DateTime(timezone=True), nullable=True))
    op.add_column('viaticos', sa.Column('firma_revisor_hash', sa.String(length=500), nullable=True))
    op.add_column('viaticos', sa.Column('firma_tesoreria_nombre', sa.String(length=200), nullable=True))
    op.add_column('viaticos', sa.Column('firma_tesoreria_fecha', sa.DateTime(timezone=True), nullable=True))
    op.add_column('viaticos', sa.Column('firma_tesoreria_hash', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viaticos', 'firma_tesoreria_hash')
    op.drop_column('viaticos', 'firma_tesoreria_fecha')
    op.drop_column('viaticos', 'firma_tesoreria_nombre')
    op.drop_column('viaticos', 'firma_revisor_hash')
    op.drop_column('viaticos', 'firma_revisor_fecha')
    op.drop_column('viaticos', 'firma_revisor_nombre')
    op.drop_column('viaticos', 'firma_jefe_hash')
    op.drop_column('viaticos', 'firma_jefe_fecha')
    op.drop_column('viaticos', 'firma_jefe_nombre')
    op.drop_column('viaticos', 'firma_solicitante_hash')
    op.drop_column('viaticos', 'firma_solicitante_fecha')
    op.drop_column('viaticos', 'firma_solicitante_nombre')
    # ### end Alembic commands ###
